definitions:
  datatypes.JSONMap:
    additionalProperties: true
    type: object
  github_com_xiaoxlm_monitor-gateway_api_request.MetricsBatchQueryBody:
    properties:
      queries:
        items:
          $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_api_request.MetricsQueryInfo'
        type: array
    required:
    - queries
    type: object
  github_com_xiaoxlm_monitor-gateway_api_request.MetricsQueryInfo:
    properties:
      end:
        description: 结束时间
        type: integer
      labelValue:
        additionalProperties:
          type: string
        type: object
      metricUniqueID:
        $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_internal_enum.MetricUniqueID'
      start:
        description: 开始时间
        type: integer
      step:
        description: 步长
        type: integer
    required:
    - end
    - labelValue
    - metricUniqueID
    - start
    - step
    type: object
  github_com_xiaoxlm_monitor-gateway_api_response.ListMetricsRESP:
    properties:
      data:
        items:
          $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_api_response.MetricsData'
        type: array
    type: object
  github_com_xiaoxlm_monitor-gateway_api_response.MetricsData:
    properties:
      hostIP:
        type: string
      metricUniqueID:
        allOf:
        - $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_internal_enum.MetricUniqueID'
        description: 指标唯一标识
      multiMetricsData:
        description: values 是否有多个值
        type: boolean
      values:
        description: 时序数值
        items:
          $ref: '#/definitions/httputil.MetricsInfo'
        type: array
    type: object
  github_com_xiaoxlm_monitor-gateway_internal_enum.MetrcisMappingCategory:
    enum:
    - CPU
    - GPU
    - NODE_MEMORY
    - DISK
    - NETWORK
    type: string
    x-enum-varnames:
    - MetrcisMappingCategory_Cpu
    - MetrcisMappingCategory_Gpu
    - MetrcisMappingCategory_Memory
    - MetrcisMappingCategory_Disk
    - MetrcisMappingCategory_Network
  github_com_xiaoxlm_monitor-gateway_internal_enum.MetricUniqueID:
    enum:
    - cpu_avg_util
    - mem_util
    - gpu_mem_avg_util
    - gpu_avg_util
    - gpu_all_util
    - gpu_avg_temp
    - disk_util
    - eth_recv_bytes_rate
    - eth_trans_bytes_rate
    - ib_recv_bytes_rate
    - ib_trans_bytes_rate
    type: string
    x-enum-varnames:
    - MetricUniqueID_Cpu_Avg_Util
    - MetricUniqueID_Mem_Util
    - MetricUniqueID_Gpu_Mem_Avg_Util
    - MetricUniqueID_Gpu_Avg_Util
    - MetricUniqueID_Gpu_All_Util
    - MetricUniqueID_Gpu_Avg_Temp
    - MetricUniqueID_Disk_Util
    - MetricUniqueID_Eth_Recv
    - MetricUniqueID_Eth_Trans
    - MetricUniqueID_IB_Recv
    - MetricUniqueID_IB_Trans
  httputil.ErrorRESP:
    properties:
      code:
        type: integer
      msg:
        type: string
    type: object
  httputil.MetricsInfo:
    properties:
      metric:
        additionalProperties:
          type: string
        type: object
      values:
        description: 时序数值
        items:
          $ref: '#/definitions/httputil.MetricsValues'
        type: array
    type: object
  httputil.MetricsValues:
    properties:
      color:
        type: string
      timestamp:
        type: integer
      value:
        type: number
    type: object
  internal_model.MetricsMapping:
    properties:
      category:
        allOf:
        - $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_internal_enum.MetrcisMappingCategory'
        description: 类别
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/mysql.DeletedTime'
      description:
        description: 描述
        type: string
      id:
        type: integer
      labels:
        allOf:
        - $ref: '#/definitions/datatypes.JSONMap'
        description: 指标标签(key:标签名；value:标签描述)
      metricUniqueID:
        allOf:
        - $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_internal_enum.MetricUniqueID'
        description: 告警唯一标识
      updatedAt:
        type: string
    type: object
  mysql.DeletedTime:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a monitor gateway
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://www.swagger.io/support
  title: monitor-gateway
  version: "1.0"
paths:
  /monitor-gateway/api/v1/metrics/batch-query:
    post:
      consumes:
      - application/json
      description: 更具PromQL查询指标
      operationId: BatchQuery
      parameters:
      - description: Authorization Basic token
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_api_request.MetricsBatchQueryBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_xiaoxlm_monitor-gateway_api_response.ListMetricsRESP'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.ErrorRESP'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorRESP'
      summary: BatchQuery
      tags:
      - BatchQuery
  /monitor-gateway/api/v1/metrics/mapping:
    get:
      consumes:
      - application/json
      description: 获取指标映射
      operationId: ListMetricsMapping
      parameters:
      - description: Authorization Basic token
        in: header
        name: Authorization
        required: true
        type: string
      - description: 类别
        enum:
        - CPU
        - GPU
        - NODE_MEMORY
        - DISK
        - NETWORK
        in: query
        name: category
        type: string
      - description: metrics唯一id
        in: query
        name: metricsUniqueID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_model.MetricsMapping'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.ErrorRESP'
      summary: ListMetricsMapping
      tags:
      - ListMetricsMapping
swagger: "2.0"
